# Generated by Django 3.1.3 on 2020-12-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fuente',
            field=models.URLField(default=11, max_length=50),
            preserve_default=False,
        ),
    ]
