# Generated by Django 3.1.3 on 2021-02-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_fuente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fuente',
            field=models.URLField(),
        ),
    ]
