# Generated by Django 3.0.3 on 2021-03-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='visitas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
