# Generated by Django 3.1.2 on 2020-11-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_auto_20201105_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='dirección',
            field=models.CharField(max_length=50, verbose_name='Su dirección'),
        ),
    ]
